# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: # Replace with a single Patreon username
ko_fi: 4xsample # Replace with a single Ko-fi username
custom: 'https://www.paypal.com/donate/?hosted_button_id=EFVMSRHVBNJP4' # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
