version: "2.1"
services:

  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Andorra

    volumes:
      - /data/container/heimdall:/config

    ports:
      - 180:80
      - 1443:443

    restart: unless-stopped