version: '2'

services:
    plex:
        image: linuxserver/plex
        container_name: plex
        restart: always
        networks:
            - media        
        ports:
            - 32400:32400
            - 32400:32400/udp
            - 32469:32469
            - 32469:32469/udp
            - 5353:5353/udp
            - 1900:1900/udp
        volumes:
            - /data/container/plex:/config
            - /media/pi/MainStorage/PlexMedia/transcode:/transcode
            - /media/pi/MainStorage/PlexMedia:/data
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Andorra

networks:
    media:
        external: true