version: '2'
serveis:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM} 
      - ADVERTISE_IP=${ADVERTISE_IP} 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Andorra
    hostname: 4XHomeServer
    volumes:
      - '/home/pi/plex/config:/config'
      - '/home/pi/plex/transcode:/transcode'
      - '/media/pi/MainStorage/PlexMedia:/data'
