version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Andorra
      - PASSWORD=${PASSWORD} #optional
#      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
#      - SUDO_PASSWORD_HASH= #optional
#      - PROXY_DOMAIN=the.proxy.domain #optional
#      - DEFAULT_WORKSPACE=/config/workspace #optional

    volumes:
      - /data/container/codeserver:/config

    ports:
      - 8443:8443

    restart: unless-stopped
