version: '2'

services:
  shellinabox:

    image: sspreitzer/shellinabox
    container_name: shellinabox
    restart: always
  
#    networks:
#      - media
  
    ports:
      - 4100:4200
  
    environment:
      - SIAB_ADDUSER=false
      - SIAB_USER=pi
      - SIAB_GROUP=pi
      - SIAB_USERID=1000
      - SIAB_GROUPID=1000
      - SIAB_PASSWORD=uger5234
      - SIAB_SHELL=/bin/bash
      - SIAB_HOME=/
      - SIAB_SUDO=true

networks:
    media:
        external: true