---
version: "2.1"
services:
    netbootxyz:
        image: ghcr.io/netbootxyz/netbootxyz
        container_name: netbootxyz
        environment:
            - MENU_VERSION=2.0.47
            - NGINX_PORT=80
            - WEB_APP_PORT=3000
        volumes:
            - /adreça/a/la/config:/config
            - /adreça/als/assets:/assets
        ports:
            - 3000:3000 #Hauria de coincidir amb "WEB_APP_PORT"
            - 69:69/udp
            - 8080:80 #Hauria de coincidir amb "NGINX_PORT"
        restart: unless-stopped
