version: '2'

services:
    organizr:
        image: organizr/organizr
        container_name: organizr
        restart: always

        ports:
            - 8811:80
            - 8444:443
        
        volumes:
            - /data/container/organizr:/config
        
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Andorra

networks:
    media:
        external: true 