version: '2'

services:
    rtorrent:

        image: linuxserver/rutorrent
        container_name: rtorrent
        restart: always
    
#        networks:
#            - media        

        ports:
            - 5000:5000
            - 6881:6881/udp
            - 8180:80
            - 51413:51413
    
        volumes:
            - /data/container/rtorrent:/config
            - /media/pi/MainStorage/Torrent:/downloads
    
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Andorra

networks:
    media:
        external: true   