version: '2'

services:
    portainer:

        image: portainer/portainer
        container_name: portainer
        restart: always

        networks:
            - media        

        ports:
            - 9000:9000

        volumes:
            - /data/container/portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock:ro

        environment:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Andorra

networks:
    media:
        external: true