services:
      mc:
            image: itzg/minecraft-server

            ports:
                  - 25565:25565
                  - 8080:8080

            environment:
                  EULA: "TRUE"
                  SERVER_NAME: "4Xland"
                  MOTD: "Benvinguts a miaucraft"
                  DIFFICULTY: "hard"
                  OVERRIDE_ICON: "true"
                  ICON: "https://static-cdn.jtvnw.net/jtv_user_pictures/aa6848c1-9699-4440-bf6e-5573a1aac9c0-profile_image-70x70.png"
                  ENABLE_RCON: "true"
                  RCON_PASSWORD: "${RCON_PASSWORD}"
                  MAX_PLAYERS: "16"
                  MAX_WORLD_SIZE: "100000"
                  ALLOW_NETHER: "true"
                  ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
                  ENABLE_COMMAND_BLOCK: "true"
                  HARDCORE: "false"
                  SPAWN_ANIMALS: "true"
                  SPAWN_MONSTERS: "true"
                  SPAWN_NPCS: "true"
                  SPAWN_PROTECTION: "0"
                  VIEW_DISTANCE: "24"
                  PVP: "true"
                  ONLINE_MODE: "true"
                  ALLOW_FLIGHT: "true"
                  GENERATE_STRUCTURES: "true"
#                 OVERRIDE_WHITELIST: "true"
                  WHITELIST: "${WHITELIST}"
#                  OVERRIDE_OPS: "true"
                  OPS: "${OPS}"
#                 PLAYER_IDLE_TIMEOUT: "30000"

#        Per habilitar els packs de recursos de vanillatweaks.net
                  REMOVE_OLD_VANILLATWEAKS: "true"
                  VANILLATWEAKS_SHARECODE: "7vAnPS"

#       Per habilitar modpacks "FTBA" es FTB "CURSEFORGE" per Curseforge
#      TYPE: "FTBA"
      
#       Per posar modpacks de FTB usant el codi numeric del modpack que apareix al costat del nom del modpack
#      FTB_MODPACK_ID:
# Molt recomanable afegir la versió que es pot trobar a la pestanya versions i clickant a la versió que toqui.
#      FTB_MODPACK_VERSION_ID:

#       Per poder triar el modpack de Curseforge s'ha d'afegir el modpack escollit 
#      CF_SERVER_MOD: ""      

            tty: true
            stdin_open: true
            restart: unless-stopped
            volumes: 
# attach a directory relative to the directory containing this compose file
                   - ./minecraft-data:/data
